[package]
name = "bfjit"
version = "0.1.1"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.24"
dynasm = "1.1.0"
dynasmrt = "1.1.0"
structopt = "0.3.21"
